version: "3.9"
services:
  backend:
    build: ./backend
    container_name: zenbody-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build: ./frontend
    container_name: zenbody-frontend
    ports:
      - "80:80"
    restart: always

